
package Tela;

import java.sql.*;
import ConexaoBanco.ModuloConexao; 
import java.awt.Color;

import javax.swing.JOptionPane;

/**
 *
 * @author UCI04
 */
public class TelaLogin extends javax.swing.JFrame {
    //usando a variavel conexao
    Connection conexao = null;
    //criando variaveis especiais para conexao com o banco de dados
    //PreparedStatement e ResultSet são frameworks do pacote java.sql
    //e servem para preparar e executar as instruções SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    //criando o metodo logar
    public void logar(){
        String sql = "select * from tbusuario where login=? and senha=?";
        try {
            //as linhas abaixo preparam a consulta ao banco em funçao do 
            //que foi digitado nas caixas de texto. o ? é substituido pelo 
            //valor das variaveis
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtusuario.getText());
            pst.setString(2, jPsenha.getText());
            //a linha abaixo executa a query
            rs = pst.executeQuery();
            //se existir usuario e senha correspondente
            if (rs.next()) {
                //a linha abaixo obtem o conteudo do campo perfil
                String perfil=rs.getString(5);
                //System.out.println(perfil);
                //a estrutura abaixo faz o tratamento do perfil do usuario
                if (perfil.equals("admin")){                 
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);
                TelaPrincipal.CadUsuario.setEnabled(true);
                TelaPrincipal.lblusuario.setText(rs.getString(2));
                TelaPrincipal.lblusuario.setForeground(Color.BLUE);
                this.dispose();
                conexao.close();
                }else{
                   TelaPrincipal principal = new TelaPrincipal();
                   principal.setVisible(true);
                   TelaPrincipal.lblusuario.setText(rs.getString(2));
                   //TelaPrincipal.lblusuario.setForeground(Color.WHITE);
                    this.dispose();
                }
            } else {
              
                JOptionPane.showMessageDialog(null, "usuario e/ou senha inválido(s)");
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public TelaLogin() {
        initComponents();
        //estabelecer a conexão com o banco sempre neste ponto
        conexao = ModuloConexao.conector(); 
        //System.out.println(conexao);
        
        if (conexao != null){
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dbok.png")));
;            
        }else {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dberror.png")));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPsenha = new javax.swing.JPasswordField();
        btlogin = new javax.swing.JToggleButton();
        btcancelar = new javax.swing.JToggleButton();
        lblStatus = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE NOTA - LOGIN");
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(txtusuario);
        txtusuario.setBounds(80, 30, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-male-user-40.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 40, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-lock-40.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 40, 50);

        jPsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPsenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jPsenha);
        jPsenha.setBounds(80, 80, 200, 20);

        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        btlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btloginKeyPressed(evt);
            }
        });
        getContentPane().add(btlogin);
        btlogin.setBounds(80, 120, 90, 23);

        btcancelar.setBackground(new java.awt.Color(204, 204, 204));
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btcancelar);
        btcancelar.setBounds(190, 120, 90, 23);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dberror.png"))); // NOI18N
        getContentPane().add(lblStatus);
        lblStatus.setBounds(290, 100, 70, 60);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/67581fee4c5d5ec.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(-10, -20, 450, 220);

        setSize(new java.awt.Dimension(382, 220));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        /*if(txtusuario.getText().equals("natan") && jPsenha.getText().equals("123")){
            TelaPrincipal tela = new TelaPrincipal();
                        tela.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "usuario ou senha ivalidos");
        }*/
        // chamando o metodo logar
        logar();
            
    }//GEN-LAST:event_btloginActionPerformed

    private void jPsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPsenhaKeyPressed
       /* if(txtusuario.getText().equals("natan") && jPsenha.getText().equals("123")){
            TelaPrincipal tela = new TelaPrincipal();
                        tela.setVisible(true);
                       
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "usuario ou senha ivalidos");
        }*/
      
    }//GEN-LAST:event_jPsenhaKeyPressed

    private void btloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btloginKeyPressed
      
    }//GEN-LAST:event_btloginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JToggleButton btcancelar;
    private javax.swing.JToggleButton btlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPsenha;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
